### ISSUE TITLE
cache error: undefined method `request_uri'

### ISSUE THREAD

**Issue by andey** [iron-io/iron_cache_rails#5]
Since I've installed iron_cache_rails, I'm continuously getting the following error.
This error happens regularly and randomly.

``````
cache error: undefined method `request_uri' for #<URI::Generic:0x00000006a4b838>
/app/vendor/bundle/ruby/1.9.1/gems/rest-2.2.0/lib/rest/wrappers/net_http_persistent_wrapper.rb:85:in `get'
/app/vendor/bundle/ruby/1.9.1/gems/rest-2.2.0/lib/rest/client.rb:124:in `block in perform_op'
/app/vendor/bundle/ruby/1.9.1/gems/rest-2.2.0/lib/rest/client.rb:110:in `perform_op'
/app/vendor/bundle/ruby/1.9.1/gems/rest-2.2.0/lib/rest/client.rb:123:in `perform_op'
/app/vendor/bundle/ruby/1.9.1/gems/rest-2.2.0/lib/rest/client.rb:86:in `get'
/app/vendor/bundle/ruby/1.9.1/gems/iron_core-0.5.1/lib/iron_core/client.rb:175:in `get'
/app/vendor/bundle/ruby/1.9.1/gems/iron_cache-1.3.0/lib/iron_cache/items.rb:21:in `get'
/app/vendor/bundle/ruby/1.9.1/gems/iron_cache-1.3.0/lib/iron_cache/caches.rb:102:in `get'
/app/vendor/bundle/ruby/1.9.1/gems/iron_cache_rails-0.1.4/lib/active_support/cache/iron_cache.rb:34:in `block in read_entry'
/app/vendor/bundle/ruby/1.9.1/gems/iron_cache_rails-0.1.4/lib/active_support/cache/iron_cache.rb:64:in `with_namespace'
/app/vendor/bundle/ruby/1.9.1/gems/iron_cache_rails-0.1.4/lib/active_support/cache/iron_cache.rb:33:in `read_entry'
/app/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.11/lib/active_support/cache/strategy/local_cache.rb:134:in `read_entry'
/app/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.11/lib/active_support/cache.rb:316:in `block in read'
/app/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.11/lib/active_support/cache.rb:520:in `instrument'
/app/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.11/lib/active_support/cache.rb:315:in `read'
/app/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.11/lib/action_dispatch/http/rack_cache.rb:17:in `read'
/app/vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/metastore.rb:30:in `lookup'
/app/vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:169:in `lookup'
/app/vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:66:in `call!'
/app/vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in `call'
/app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.11/lib/rails/engine.rb:479:in `call'
/app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.11/lib/rails/application.rb:223:in `call'
/app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.11/lib/rails/railtie/configurable.rb:30:in `method_missing'
/app/vendor/bundle/ruby/1.9.1/gems/thin-1.5.0/lib/thin/connection.rb:81:in `block in pre_process'
/app/vendor/bundle/ruby/1.9.1/gems/thin-1.5.0/lib/thin/connection.rb:79:in `catch'
/app/vendor/bundle/ruby/1.9.1/gems/thin-1.5.0/lib/thin/connection.rb:79:in `pre_process'
/app/vendor/bundle/ruby/1.9.1/gems/thin-1.5.0/lib/thin/connection.rb:54:in `process'
/app/vendor/bundle/ruby/1.9.1/gems/thin-1.5.0/lib/thin/connection.rb:39:in `receive_data'
/app/vendor/bundle/ruby/1.9.1/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in `run_machine'
/app/vendor/bundle/ruby/1.9.1/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in `run'
/app/vendor/bundle/ruby/1.9.1/gems/thin-1.5.0/lib/thin/backends/base.rb:63:in `start'
/app/vendor/bundle/ruby/1.9.1/gems/thin-1.5.0/lib/thin/server.rb:159:in `start'
/app/vendor/bundle/ruby/1.9.1/gems/thin-1.5.0/lib/thin/controllers/controller.rb:86:in `start'
/app/vendor/bundle/ruby/1.9.1/gems/thin-1.5.0/lib/thin/runner.rb:187:in `run_command'
/app/vendor/bundle/ruby/1.9.1/gems/thin-1.5.0/lib/thin/runner.rb:152:in `run!'
/app/vendor/bundle/ruby/1.9.1/gems/thin-1.5.0/bin/thin:6:in `<top (required)>'
/app/vendor/bundle/ruby/1.9.1/bin/thin:19:in `load'
/app/vendor/bundle/ruby/1.9.1/bin/thin:19:in `<main>'```
``````

Using:
iron_cache (1.3.0)
iron_cache_rails (0.1.4)
iron_core (0.5.1)

**Comment by treeder** [comment]
Can you try updating to iron_cache 1.4 and see if you still get it?

**Comment by andey** [comment]
I've upgraded to 1.4.0 and I'm still seeing the error.
However, I've narrowed down the problem to rails fragment caching with a new key.

```
cache error: undefined method `request_uri' for #<URI::Generic:0x000000050022b0>
/app/vendor/bundle/ruby/1.9.1/gems/rest-2.2.0/lib/rest/wrappers/net_http_persistent_wrapper.rb:85:in `get'
/app/vendor/bundle/ruby/1.9.1/gems/rest-2.2.0/lib/rest/client.rb:124:in `block in perform_op'
/app/vendor/bundle/ruby/1.9.1/gems/rest-2.2.0/lib/rest/client.rb:110:in `perform_op'
/app/vendor/bundle/ruby/1.9.1/gems/rest-2.2.0/lib/rest/client.rb:123:in `perform_op'
/app/vendor/bundle/ruby/1.9.1/gems/rest-2.2.0/lib/rest/client.rb:86:in `get'
/app/vendor/bundle/ruby/1.9.1/gems/iron_core-0.5.1/lib/iron_core/client.rb:175:in `get'
/app/vendor/bundle/ruby/1.9.1/gems/iron_cache-1.4.0/lib/iron_cache/items.rb:21:in `get'
/app/vendor/bundle/ruby/1.9.1/gems/iron_cache-1.4.0/lib/iron_cache/caches.rb:102:in `get'
/app/vendor/bundle/ruby/1.9.1/gems/iron_cache_rails-0.1.4/lib/active_support/cache/iron_cache.rb:34:in `block in read_entry'
/app/vendor/bundle/ruby/1.9.1/gems/iron_cache_rails-0.1.4/lib/active_support/cache/iron_cache.rb:64:in `with_namespace'
/app/vendor/bundle/ruby/1.9.1/gems/iron_cache_rails-0.1.4/lib/active_support/cache/iron_cache.rb:33:in `read_entry'
/app/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.11/lib/active_support/cache/strategy/local_cache.rb:134:in `read_entry'
/app/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.11/lib/active_support/cache.rb:316:in `block in read'
/app/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.11/lib/active_support/cache.rb:520:in `instrument'
/app/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.11/lib/active_support/cache.rb:315:in `read'
/app/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.11/lib/action_dispatch/http/rack_cache.rb:17:in `read'
/app/vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/metastore.rb:30:in `lookup'
/app/vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:169:in `lookup'
/app/vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:66:in `call!'
/app/vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in `call'
/app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.11/lib/rails/engine.rb:479:in `call'
/app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.11/lib/rails    /application.rb:223:in `call'
/app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.11/lib/rails/railtie/configurable.rb:30:in `method_missing'
/app/vendor/bundle/ruby/1.9.1/gems/thin-1.5.0/lib/thin/connection.rb:81:in `block in pre_process'
/app/vendor/bundle/ruby/1.9.1/gems/thin-1.5.0/lib/thin/connection.rb:79:in `catch'
/app/vendor/bundle/ruby/1.9.1/gems/thin-1.5.0/lib/thin/connection.rb:79:in `pre_process'
/app/vendor/bundle/ruby/1.9.1/gems/thin-1.5.0/lib/thin/connection.rb:54:in `process'
/app/vendor/bundle/ruby/1.9.1/gems/thin-1.5.0/lib/thin/connection.rb:39:in `receive_data'
/app/vendor/bundle/ruby/1.9.1/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in `run_machine'
/app/vendor/bundle/ruby/1.9.1/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in `run'
/app/vendor/bundle/ruby/1.9.1/gems/thin-1.5.0/lib/thin/backends/base.rb:63:in `start'
/app/vendor/bundle/ruby/1.9.1/gems/thin-1.5.0/lib/thin/server.rb:159:in `start'
/app/vendor/bundle/ruby/1.9.1/gems/thin-1.5.0/lib/thin/controllers/controller.rb:86:in `start'
/app/vendor/bundle/ruby/1.9.1/gems/thin-1.5.0/lib/thin/runner.rb:187:in `run_command'
/app/vendor/bundle/ruby/1.9.1/gems/thin-1.5.0/lib/thin/runner.rb:152:in `run!'
/app/vendor/bundle/ruby/1.9.1/gems/thin-1.5.0/bin/thin:6:in `<top (required)>'
/app/vendor/bundle/ruby/1.9.1/bin/thin:19:in `load'
/app/vendor/bundle/ruby/1.9.1/bin/thin:19:in `<main>'
```

**Comment by treeder** [comment]
A new key as in one that you set or is it randomly generated?  It may be creating a bad URL if they key has invalid characters. 

@iced thoughts?

**Comment by andey** [comment]
I'm using the Rails automatically generated cache_key.
An example of a key:

```
amas/1213-20130119060739
```

**Comment by ghost** [comment]
I just encountered this error myself,
any solution?

**Comment by iced** [comment]
show us stacktrace please

**Comment by ghost** [comment]
not easy to access that at the moment,
I just discovered that I cannot use a "/" in the key string, so I worked around it by replacing them all with "-"
